# Generated by Django 4.1.5 on 2023-02-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookloan",
            name="status",
            field=models.CharField(
                choices=[
                    ("0", "Requested"),
                    ("1", "Issued"),
                    ("2", "Rejected"),
                    ("3", "Returned"),
                ],
                default="0",
                max_length=10,
            ),
        ),
    ]
