# Generated by Django 4.1.5 on 2023-01-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("m", "Male"), ("f", "Female"), ("other", "Other")],
                max_length=20,
            ),
        ),
    ]
