# Generated by Django 4.1.5 on 2023-02-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_bookloan_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookloan",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("issued", "Issued"),
                    ("rejected", "Rejected"),
                    ("returned", "Returned"),
                ],
                default="requested",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="bookrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
    ]
