# Generated by Django 4.1.5 on 2023-02-27 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookloan",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to="core.book",
            ),
        ),
        migrations.AlterField(
            model_name="bookloan",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    ("0", "Requested"),
                    ("1", "Issued"),
                    ("2", "Rejected"),
                    ("3", "Returned"),
                ],
                default="0",
            ),
        ),
        migrations.AlterField(
            model_name="bookrequest",
            name="status",
            field=models.SmallIntegerField(
                choices=[("0", "Pending"), ("1", "Approved"), ("2", "Rejected")],
                default="0",
            ),
        ),
        migrations.AlterField(
            model_name="bookrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="books",
            field=models.ManyToManyField(through="core.BookLoan", to="core.book"),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.SmallIntegerField(
                blank=True, choices=[("0", "Male"), ("1", "Female"), ("2", "Other")]
            ),
        ),
    ]
