# Generated by Django 4.1.5 on 2023-02-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_bookloan_status_alter_bookrequest_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.SmallIntegerField(
                blank=True,
                choices=[("0", "Male"), ("1", "Female"), ("2", "Other")],
                null=True,
            ),
        ),
    ]
