# Generated by Django 4.1.5 on 2023-03-03 10:18

from django.db import migrations, models


def migrate_str_to_int_bookloan(apps, schema_editor):

    MyModel = apps.get_model('core', 'bookloan')

    for mm in MyModel.objects.all():
        status_old = mm.status_old
        status_new_int = int(status_old)
        mm.status = status_new_int 
        mm.save()


def migrate_str_to_int_bookrequest(apps, schema_editor):

    MyModel = apps.get_model('core', 'bookrequest')

    for mm in MyModel.objects.all():
        status_old = mm.status_old
        status_new_int = int(status_old)
        mm.status = status_new_int 
        mm.save()


def migrate_str_to_int_user(apps, schema_editor):

    MyModel = apps.get_model('core', 'user')

    for mm in MyModel.objects.all():
        gender_old = mm.gender_old
        gender_new_int = int(gender_old)
        mm.gender = gender_new_int 
        mm.save()

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_user_gender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookloan",
            old_name="status",
            new_name="status_old",
        ),
        migrations.AddField(
            model_name="bookloan",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    ("0", "Requested"),
                    ("1", "Issued"),
                    ("2", "Rejected"),
                    ("3", "Returned"),
                ],
                default="0",
            ),
        ),
        migrations.RunPython(migrate_str_to_int_bookloan),
        migrations.RemoveField(
            model_name='bookloan',
            name='status_old',
        ),
        migrations.RenameField(
            model_name="bookrequest",
            old_name="status",
            new_name="status_old",
        ),
        migrations.AddField(
            model_name="bookrequest",
            name="status",
            field=models.SmallIntegerField(
                choices=[("0", "Pending"), ("1", "Approved"), ("2", "Rejected")],
                default="0",
            ),
        ),
        migrations.RunPython(migrate_str_to_int_bookrequest),
        migrations.RemoveField(
            model_name='bookrequest',
            name='status_old',
        ),
        migrations.RenameField(
            model_name="user",
            old_name="gender",
            new_name="gender_old",
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.SmallIntegerField(
                blank=True,
                choices=[("0", "Male"), ("1", "Female"), ("2", "Other")],
                null=True,
            ),
        ),
        migrations.RunPython(migrate_str_to_int_user),
        migrations.RemoveField(
            model_name='user',
            name='gender_old',
        ),
    ]
